CREATE TABLE `sys_user` (
  `IDSYS_USER` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `USER_NAME` VARCHAR(45) NULL COMMENT '',
  `PASSWORD` VARCHAR(100) NULL COMMENT '',
  `USER_ENABLED` BIT NULL DEFAULT 1 COMMENT '',
  `LOGIN_ATTEMPTS` INT NULL DEFAULT 0 COMMENT '',
  `LAST_LOGIN` DATE NULL COMMENT '',
  `EXPIRATION_DATE` DATE NULL COMMENT '',
  `EMAIL` VARCHAR(80) NULL COMMENT '',
  PRIMARY KEY (`IDSYS_USER`)  COMMENT '',
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC)  COMMENT '');

  CREATE TABLE `sys_role` (
  `ROLE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ROLE_NAME` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`ROLE_ID`)  COMMENT '',
  UNIQUE INDEX `ROLE_NAME_UNIQUE` (`ROLE_NAME` ASC)  COMMENT '');

CREATE TABLE `sys_user_role` (
  `USER_ROLE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `IDSYS_USER` INT NULL COMMENT '',
  `ROLE_ID` INT NULL COMMENT '',
  PRIMARY KEY (`USER_ROLE_ID`)  COMMENT '');

ALTER TABLE `sys_user_role` 
ADD INDEX `FK_IDSYS_USERx` (`IDSYS_USER` ASC)  COMMENT '',
ADD INDEX `FK_ROLE_idx` (`ROLE_ID` ASC)  COMMENT '';
ALTER TABLE `sys_user_role` 
ADD CONSTRAINT `FK_USER`
  FOREIGN KEY (`IDSYS_USER`)
  REFERENCES `sys_user` (`IDSYS_USER`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `FK_ROLE`
  FOREIGN KEY (`ROLE_ID`)
  REFERENCES `sys_role` (`ROLE_ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

INSERT INTO `sys_role` (`ROLE_NAME`) VALUES ('REG_USER');
INSERT INTO `sys_role` (`ROLE_NAME`) VALUES ('ROLE_SUPER');
INSERT INTO `sys_role` (`ROLE_NAME`) VALUES ('ROLE_ADMIN');